config/routes.rb
Rails.application.routes.draw do
  mount Api => '/'

  devise_for :users

  get 'timers/manual' => 'timers#manual'
  post 'timers/manual' => 'timers#manual'

  resources :timers, :except => :show do
    put 'start' => 'timers#start', :as => :start
    put 'stop' => 'timers#stop', :as => :stop
  end

  root :to => 'timers#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Timer do |timer|
      timer.user == user
    end
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user

  extend Enumerize
  enumerize :role, :in => [:administrator], :predicates => true
end

app/models/timer.rb
class Timer < ActiveRecord::Base
  attr_accessor :time, :date

  belongs_to :user

  extend Enumerize
  enumerize :kind, :in => [:design, :content, :copyright, :management, :develop, :not_planned_develop, :sysop, :support, :meeting], :default => :develop

  validates_presence_of :title

  scope :active, ->{ where(:active => true) }
  scope :today,  ->{ where('timers.start_at >= ? AND timers.end_at <= ?', Time.zone.now.beginning_of_day, Time.zone.now.end_of_day) }
  scope :by_title_and_kind, -> (title, kind) { where('timers.title = ? AND timers.kind = ?', title, kind) }
  scope :by_period, ->(from, to) { where('timers.start_at >= ? AND timers.end_at <= ?', Date.parse(from).beginning_of_day, Date.parse(to).end_of_day) if from && to }

  def by_day
    start_at.to_date
  end

  def spend_time
    if active?
      @spend_time = amount.to_i + Time.zone.now.to_i - start_at.to_time.to_i
    else
      @spend_time = amount.to_i
    end
  end

  def manual_timer(date, time)
    self.update_attributes!(:active => false, :amount => parsed_time(time), :start_at => date, :end_at => (date.to_time + parsed_time(time)))
  end

  def parsed_time(time)
    regex = time.match(/(?<hours>\d+(h|р))?(?<minutes>(?<=h)?\d+(m|ь))?(?<seconds>(?<=m)?\d+(s|ы))?/)

    hours   = regex[1].to_i
    minutes = regex[2].to_i
    seconds = regex[3].to_i

    @parsed_time ||= hours * 60 * 60 + minutes * 60 + seconds
  end


  def start!
    if self.start_at >= Time.zone.now.beginning_of_day
      start_today_timer
    elsif find_eldest_timers.any?
      start_eldest_timer
    else
      create_new_timer
    end
  end

  def stop!
    self.update_attributes!(:active => false, :amount => self.spend_time, :end_at => Time.zone.now)
  end

  private

  def find_eldest_timers
    Timer.where(:title => self.title, :kind => self.kind, :user_id => self.user_id).today
  end

  def start_today_timer
    self.update_attributes!(:active => true, :start_at => Time.zone.now)
  end

  def start_eldest_timer
    timer = Timer.where(:title => self.title, :kind => self.kind).today.first

    timer.update_attributes!(:active => true, :start_at => Time.zone.now)
  end

  def create_new_timer
    Timer.create!(:title => self.title, :kind => self.kind, :start_at => Time.zone.now, :user_id => self.user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :permissions, :dependent => :destroy
  has_many :timers, -> { order('start_at desc') } , :dependent => :destroy

  def administrator?
    permissions.where(:role => :administrator).any?
  end

  def stop_all_active_timers
    timers.active.map { |timer| timer.update_attributes(:active => false, :amount => timer.spend_time, :end_at => Time.zone.now) }
  end

  def remember_me
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :with => :exception

  before_filter :authenticate_user!

  layout 'public'

  rescue_from CanCan::AccessDenied do |exception|
    render file: "#{Rails.root}/public/403", formats: [:html], status: 403, layout: false
  end

  private

  def after_sign_in_path_for(resource)
    timers_path
  end
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  inherit_resources
  load_and_authorize_resource

  actions :all, :except => :show
  custom_actions :collection => [:start, :stop, :manual]

  before_filter :stop_all_active_timers, :only => [:create, :start, :stop]

  def create
    if params[:timer][:date] || params[:timer][:time]
      @timer = current_user.timers.new(timer_params)

      @timer.manual_timer(params[:timer][:date], params[:timer][:time])

      redirect_to timers_path
    else
      create!
    end
  end

  def start
    start!{
      @timer = Timer.find(params[:timer_id])

      @timer.start!

      render :partial => 'timers/list', :locals => { :collection => @collection } and return
    }
  end

  def stop
    stop!{
      @timer = Timer.find(params[:timer_id])

      @timer.stop!

      render :partial => 'timers/list', :locals => { :collection => @collection } and return
    }
  end

  private

  def stop_all_active_timers
    current_user.stop_all_active_timers
  end

  def collection
    @presenter = TimerPresenter.new(params.merge!(:current_user => current_user))

    @collection ||= Kaminari.paginate_array(@presenter.collection).page(params[:page])
  end

  def permitted_params
    params.permit(:timer => [:title, :kind, :date, :time])
  end

  def timer_params
    params.require(:timer).permit(:title, :kind, :date, :time)
  end

  alias_method :old_build_resource, :build_resource

  def build_resource
    old_build_resource.tap do |object|
      object.user   = current_user
      object.start_at ||= Time.zone.now
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_title
    [page_title, I18n.t('site_name')].compact.join(' / ')
  end

  def page_title(title = nil)
    @page_title ||= I18n.t("page_title.#{controller_name}.#{action_name}", :title => title).html_safe
  end
end

app/helpers/time_format_helper.rb
module TimeFormatHelper
  def timestamp_to_hours(secs, options = {})

    hours = (secs / (60 * 60)).floor
    hours = '0' + hours.to_s if hours < 10

    divisor_for_minutes = secs % (60 * 60)
    minutes = (divisor_for_minutes / 60).floor
    minutes = '0' + minutes.to_s if minutes < 10

    divisor_for_seconds = divisor_for_minutes % 60
    seconds = (divisor_for_seconds).ceil
    seconds = '0' + seconds.to_s if seconds < 10

    if options[:short].present? && hours.to_i.zero?
      return "#{minutes}:#{seconds}"
    else
      return "#{hours}:#{minutes}:#{seconds}"
    end
  end
end

app/views/commons/_filter.html.erb
<div class="btn-toolbar js-filter">
  <% if @presenter %>
    <div class="btn-group btn-toolbar filter hidden-sm hidden-xs" role="toolbar">
      <% @presenter.period_filter.links.each do |link| %>
        <%= link_to link.title, link.path, :class => "btn btn-sm btn-link #{link.klass}", :data => { :push => true } %>
      <% end %>
    </div>
  <% end %>

  <div class="btn-group btn-toolbar filter filter-green pull-right" role="toolbar">
    <%= link_to 'Добавить время', timers_manual_path, :class => 'btn btn-sm btn-link', :data => { :push => true } %>
  </div>
  <div class="btn-group btn-toolbar filter filter-green pull-right" role="toolbar">
    <%= link_to 'Запустить таймер', new_timer_path, :class => 'btn btn-sm btn-link', :data => { :push => true } %>
  </div>
</div>

app/views/commons/_header.html.erb
<%= link_to root_path, :class => 'navbar-brand' do %>
  <span class="logo"></span>
  timer.helpdeskapp.ru
<% end %>

<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right navbar-profile">
    <li class="dropdown profile-dropdown">
      <%= link_to '#', :class => 'dropdown-toggle', :data => { :toggle => :dropdown } do %>
        <%= image_tag current_user.gravatar_url, :class => 'img-avatar img-circle' %>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'Редактировать профиль', edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Выход', destroy_user_session_path, :method => :delete %></li>
      </ul>
    </li>
  </ul>
<% else %>
<% end %>

app/views/commons/_page_title.html.erb
<div class="js-page-title hidden">
  <%= document_title %>
</div>

app/views/commons/_sidebar.html.erb
<ul class="sidebar-nav">
  <li class="sidebar-brand opened">
    <%= link_to '', root_path, :class => 'navbar-brand' %>
  </li>

  <% if content_for?(:sidebar) %>
    <%= yield(:sidebar) %>
  <% else %>
    <ul class="main-nav opened">

      <li class="icon issues">
        <%= link_to root_path do %>
          <span class="pe-7s-drawer pe-2x pe-va"></span> &nbsp;
          <span class="js-toggle-title">
            Задачи
          </span>
        <% end %>
      </li>

    </ul>
  <% end %>
</ul>

<div class="settings">
  <ul>
    <li>
      <%= link_to edit_user_registration_path do %>
        <span class="pe-7s-config pe-2x pe-va"></span> &nbsp;
        <span class="js-toggle-title">
          Редактировать профиль
        </span>
      <% end %>
    </li>
  </ul>
</div>

<div class="account media">
  <div class="pull-left">
    <%= image_tag current_user.gravatar_url, :class => 'img-avatar img-circle' %>
    <%= link_to current_user, '#', :class => 'login' %>
  </div>

  <div class="logout pull-right">
    <%= link_to destroy_user_session_path, :method => :delete do %>
      <span class="pe-7s-upload pe-rotate-90 pe-2x pe-va"></span>
    <% end %>
  </div>
</div>

<div class="sidebar-toggle js-sidebar-toggle">‹</div>

app/views/layouts/_wiselinks.html.erb
<%= yield %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" sizes="192x192" href="/assets/icons/apple-touch-icon-192px.png">
    <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/assets/icons/apple-touch-icon-180px.png">
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/icons/apple-touch-icon-152px.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/icons/apple-touch-icon-144px.png">
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/icons/apple-touch-icon-120px.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/icons/apple-touch-icon-114px.png">
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/assets/icons/apple-touch-icon-76px.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/icons/apple-touch-icon-72px.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/icons/apple-touch-icon-57px.png">

    <%= favicon_link_tag 'favicon.ico'%>

    <title><%= document_title %></title>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= wiselinks_meta_tag %>
  </head>
  <body class="<%= controller_name %>">

    <header class="navbar navbar-static-top header" role="banner">
      <div class="container">
        <nav class="navbar-collapse" role="navigation">
          <%= render 'commons/header' %>
        </nav>
      </div>
    </header>

    <% if user_signed_in? %>
      <div class="timer-filter">
        <div class="container">
          <%= render 'commons/filter' %>
        </div>
      </div>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 main">
          <div class="js-wiselinks-content">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <%= render :partial => 'commons/flash' %>

    <%= render :partial => 'commons/metrika' if Rails.env.production? %>
  </body>
</html>

app/views/layouts/public.html.erb
<%= content_for :content do %>
  <%= yield %>
<% end %>

<%= render :file => 'layouts/base' %>

app/views/timers/_form.html.erb
<%= simple_form_for @timer, :html => { :class => 'form-inline form-timer' } do |f| %>
  <%= f.input :title, :as => :string, :label => false, :autofocus => true,
              :input_html => { :class => 'title js-focused-input' },
              :wrapper_html => { :class => 'title-wrapper' },
              :placeholder => 'Чем вы занимаетесь?' %>

  <%= f.input :kind, :label => false, :include_blank => false, :wrapper_html => { :class => 'kind-wrapper' } %>
  <%= f.input :time, :label => false, :placeholder => '1h30m15s',
              :input_html => { :class => 'timer-time' },
              :wrapper_html => { :class => 'time-wrapper' } unless @timer.new_record? %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'btn btn-blue' %>
    <%= link_to 'Отмена', timers_path, :class => 'btn btn-gray', :data => { :push => true } %>
  </div>
<% end %>

app/views/timers/_list.html.erb
<%= render 'commons/page_title' %>

<% @collection.group_by(&:by_day).sort.reverse.each do |day, timers| %>
  <h4>
    <%= l day, :format => :long %>,
    <span class="clock" data-clock="<%= timers.map(&:amount).sum %>"></span>
  </h4>

  <ul class="timers">
    <%= render timers %>
  </ul>
<% end %>

<%= paginate @collection %>

app/views/timers/_timer.html.erb
<li class="timer <%= timer.active? ? 'active' : 'stub' %> js-timer">
  <div class="left">
    <div class="title">
      <%= link_to timer.title, edit_timer_path(timer), :data => { :push => true } %>
    </div>

    <div class="kind pull-left hidden-xs hidden-sm">
      <%= timer.kind_text %>
    </div>
  </div>

  <div class="right">
    <div class="amount clock <%= timer.active? ? 'js-clock' : 'stub' %>" data-clock="<%= timer.spend_time %>">
      <%= timestamp_to_hours timer.amount %>
    </div>

    <div class="actions">
      <% if timer.active? %>
        <%= link_to 'Остановить', timer_stop_path(timer, :from => params[:from], :to => params[:to]), :method => :put, :class => 'btn btn-red js-stop', :remote => true %>
      <% else %>
        <%= link_to 'Запустить', timer_start_path(timer, :from => params[:from], :to => params[:to]), :method => :put, :class => 'btn btn-red js-start', :remote => true %>
      <% end %>
      <%= link_to 'Удалить', timer_path(timer), :method => :delete, :class => 'btn btn-red', :data => { :confirm => t('confirm.delete') } %>
    </div>
  </div>
</li>

app/views/timers/edit.html.erb
<%= render 'commons/page_title' %>

<div class="js-wiselinks-content">
  <h4>Редактирование таймера</h4>

  <%= render 'form' %>
</div>

app/views/timers/index.html.erb
<div class="js-timers">
  <%= render 'list' %>
</div>

app/views/timers/manual.html.erb
<%= render 'commons/page_title' %>

<div class="js-wiselinks-content">
  <h4>Добавление времени</h4>

  <%= simple_form_for Timer.new, :html => { :class => 'form-inline form-timer' } do |f| %>
    <%= f.input :title, :as => :string, :label => false, :autofocus => true,
                :input_html => { :class => 'title js-focused-input' },
                :wrapper_html => { :class => 'title-wrapper' },
                :placeholder => 'Чем вы занимаетесь?' %>

    <%= f.input :kind, :label => false, :include_blank => false, :wrapper_html => { :class => 'kind-wrapper' } %>

    <%= f.input :date, :label => false,
                :input_html => { :class => 'js-timepicker', :value => Russian::strftime(Time.zone.now.to_date, '%d-%m-%Y') },
                :wrapper_html => { :class => 'date-wrapper' } %>

    <%= f.input :time, :label => false, :placeholder => '1h30m15s',
                :input_html => { :class => 'timer-time' },
                :wrapper_html => { :class => 'time-wrapper' } %>

    <div class="actions">
      <%= f.submit 'Сохранить', :class => 'btn btn-blue' %>
      <%= link_to 'Отмена', timers_path, :class => 'btn btn-gray', :data => { :push => true } %>
    </div>
  <% end %>
</div>

app/views/timers/new.html.erb
<%= render 'commons/page_title' %>

<div class="js-wiselinks-content">
  <h4>Новый таймер</h4>

  <%= render 'form' %>
</div>